import {test} from 'node:test';
import assert from 'node:assert/strict';
import {seed,plan,match,validateAssignments,dataset} from '../lib/rescue.ts';
import {createStore,toolDefinitions} from '../lib/store.ts';

test('base scenario allocates all 480 portions without violating constraints',()=>{const s=seed(),p=plan(s);assert.equal(p.portions,480);assert.equal(p.unassigned,0);assert.deepEqual(validateAssignments(s,p.assignments),[])});
test('diet and allergen restrictions exclude otherwise nearby matches',()=>{const s=seed();assert.equal(match(s,s.donors[0],s.kitchens[3]).eligible,false);assert.match(match(s,s.donors[0],s.kitchens[3]).failures.join(' '),/sesame/);assert.equal(match(s,s.donors[5],s.kitchens[0]).eligible,false)});
test('max-flow reroutes a flexible offer instead of stranding a restricted offer',()=>{const s=seed();s.donors=[{...s.donors[0],id:'a',portions:10,diet:'vegan',allergens:[]},{...s.donors[1],id:'b',portions:10,diet:'vegetarian',allergens:[]}];s.kitchens=[{...s.kitchens[0],id:'x',capacity:10,diet:'vegetarian'},{...s.kitchens[1],id:'y',capacity:10,diet:'vegan'}];const p=plan(s);assert.equal(p.portions,20);assert.ok(p.assignments.find(a=>a.donorId==='b'&&a.kitchenId==='x'))});
test('capacity drop preserves protected 120 portions and exposes the 70-portion gap',()=>{const s=seed();s.approved=plan(s).assignments.map(a=>({...a,locked:a.id==='d1-k1'}));s.kitchens[1].capacity=30;const p=plan(s);assert.equal(p.portions,410);assert.equal(p.unassigned,70);assert.deepEqual(p.assignments.find(a=>a.id==='d1-k1'),s.approved.find(a=>a.id==='d1-k1'));assert.deepEqual(validateAssignments(s,p.assignments),[])});
test('infeasible protected commitments fail rather than silently move',()=>{const s=seed();s.approved=plan(s).assignments.map(a=>({...a,locked:a.id==='d1-k1'}));s.kitchens[0].capacity=10;assert.throws(()=>plan(s),/Protected commitments conflict/)});
test('time and max travel limits exclude unreachable meals',()=>{const s=seed();s.now=1200;assert.equal(plan(s).portions,0);s.now=1020;s.maxMinutes=5;assert.equal(plan(s).portions,0)});
test('what-if tool is read-only and mutation tools reject stale revision',()=>{const store=createStore();const tools=Object.fromEntries(toolDefinitions(store).map(t=>[t.name,t]));const before=JSON.stringify(store.get());assert.equal(tools.preview_plan.execute({capacities:[{id:'k2',capacity:30}]}).portions,410);assert.equal(JSON.stringify(store.get()),before);tools.stage_plan.execute({expected_revision:0});assert.throws(()=>tools.update_kitchen_capacities.execute({expected_revision:0,updates:[{id:'k2',capacity:30}]}),/Stale workspace/);assert.equal(store.get().kitchens[1].capacity,100)});
test('invalid batched update is atomic and does not invalidate existing proposal',()=>{const store=createStore();store.stage('rescue');const before=JSON.stringify(store.get());assert.throws(()=>store.update([{id:'k1',capacity:1},{id:'not-real',capacity:20}]));assert.equal(JSON.stringify(store.get()),before);assert.throws(()=>store.update([{id:'k1',capacity:-1}]));assert.equal(JSON.stringify(store.get()),before)});
test('human approval, locking, invalidation, and undo preserve a monotonic revision',()=>{const store=createStore();store.stage('rescue');store.approve();store.lock('d1-k1');store.update([{id:'k2',capacity:30}]);store.stage('rescue');assert.equal(store.get().proposal.portions,410);store.undo();assert.equal(store.get().revision,6);assert.equal(store.get().proposal,null);assert.equal(store.get().approved.find(a=>a.id==='d1-k1').locked,true)});
test('capacity changes invalidate proposals and export requires human approval',()=>{const store=createStore(),tools=Object.fromEntries(toolDefinitions(store).map(t=>[t.name,t]));assert.throws(()=>tools.export_approved_manifest.execute({}),/No approved/);store.stage('rescue');store.update([{id:'k2',capacity:30}]);assert.throws(()=>store.approve(),/stale/);store.stage('rescue');store.approve();assert.equal(tools.export_approved_manifest.execute({}).rows.reduce((n,r)=>n+r.portions,0),410);assert.ok(!tools.approve_plan)});
test('dataset import rejects duplicates, invalid portions and nonfinite values',()=>{const {donors,kitchens,now,maxMinutes}=seed();const data={donors,kitchens,now,maxMinutes};assert.equal(dataset(data).donors.length,6);assert.throws(()=>dataset({...data,donors:[donors[0],donors[0]]}),/unique/);assert.throws(()=>dataset({...data,now:NaN}));assert.throws(()=>dataset({...data,donors:[{...donors[0],portions:0}]}));assert.throws(()=>dataset({...data,extra:'unsafe'}),/Unknown/)});
test('min-cost objective never exceeds earliest-first travel cost at equal flow',()=>{const s=seed();s.kitchens[1].capacity=30;const a=plan(s,'rescue'),b=plan(s,'distance');assert.equal(a.portions,b.portions);assert.ok(b.score<=a.score);assert.deepEqual(validateAssignments(s,b.assignments),[])});
