'use client';
import {useState} from 'react';
import {ArrowUpRight,Leaf,Sparkles,CircleHelp,ArrowRight,Clock3,MapPin,LayoutDashboard,HandHeart,Radio,LockKeyhole,Unlock,Check,RotateCcw,Download,Upload,History,Settings2,TriangleAlert,Copy,CheckCheck,Braces,X,Undo2,ArrowDownUp} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {useRescue} from '@/lib/use-rescue';
import {plan,time,manifest,validateAssignments,seed,type Assignment,type Workspace} from '@/lib/rescue';
import {toolDefinitions} from '@/lib/store';

function download(name:string,text:string,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function csvCell(value:unknown){let s=String(value);if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'}
function Network({state,assignments}:{state:Workspace;assignments:Assignment[]}){
 const donors=state.donors.slice(0,6),kitchens=state.kitchens.slice(0,5);const maxRows=Math.max(donors.length,kitchens.length);const h=55+maxRows*43;
 return <div className="network"><svg viewBox={`0 0 640 ${h}`} role="img" aria-label={`Rescue network with ${assignments.length} proposed connections`}><defs><pattern id="dots" width="13" height="13" patternUnits="userSpaceOnUse"><circle cx="2" cy="2" r=".7" fill="#dce4d5"/></pattern></defs><rect width="640" height={h} fill="url(#dots)"/><text x="24" y="24" className="network-label">FOOD DONORS</text><text x="415" y="24" className="network-label">COMMUNITY KITCHENS</text>
 {assignments.map(a=>{const di=donors.findIndex(d=>d.id===a.donorId),ki=kitchens.findIndex(k=>k.id===a.kitchenId);if(di<0||ki<0)return null;return <path key={a.id} d={`M 218 ${52+di*43} C 300 ${52+di*43}, 340 ${52+ki*43}, 412 ${52+ki*43}`} fill="none" stroke={a.locked?'#bb8b39':'#67965a'} strokeWidth={Math.max(2,Math.min(10,a.portions/13))} opacity=".45" className="flow-path"><title>{`${a.portions} portions · ${a.locked?'Protected commitment':'Planned assignment'}`}</title></path>})}
 {!assignments.length&&<><path d={`M218 52 C315 52 315 138 412 138 M218 95 C315 95 315 52 412 52 M218 181 C315 181 315 95 412 95`} stroke="#d2dcc7" fill="none" strokeDasharray="5 5"/><text x="273" y={h-20} className="network-label">AWAITING A PLAN</text></>}
 {donors.map((d,i)=>{const assigned=assignments.filter(a=>a.donorId===d.id).reduce((n,a)=>n+a.portions,0);return <g key={d.id}><rect x="24" y={37+i*43} width="194" height="31" rx="6" fill="#f4f7ec" stroke="#d5dfc4"/><text x="35" y={57+i*43} className="node-number">{String(i+1).padStart(2,'0')}</text><text x="57" y={57+i*43} className="node-name">{d.name.length>20?d.name.slice(0,19)+'…':d.name}</text><title>{`${d.name}: ${assigned} of ${d.portions} portions assigned`}</title><circle cx="218" cy={52+i*43} r="3" fill="#9aaf6d"/></g>})}
 {kitchens.map((k,i)=><g key={k.id}><rect x="412" y={37+i*43} width="204" height="31" rx="6" fill={k.capacity?'#eef4eb':'#f6eae3'} stroke={k.capacity?'#c5d8c1':'#d9baaa'}/><circle cx="412" cy={52+i*43} r="3" fill="#5f8355"/><text x="424" y={57+i*43} className="node-name">{k.name.length>18?k.name.slice(0,17)+'…':k.name}</text><text x="603" y={57+i*43} textAnchor="end" className="node-number">{k.capacity}</text><title>{`${k.name}: capacity ${k.capacity}`}</title></g>)}
 </svg>{(state.donors.length>6||state.kitchens.length>5)&&<small className="network-overflow">Showing first 6 donors and 5 kitchens. All records are included in the plan below.</small>}</div>
}
const agentPrompt='Read my Second Serve workspace. Compare rescuing the earliest-expiring food with minimizing travel. Explain any meals left unassigned, then stage the earliest-expiry plan for my review. Preserve all protected commitments.';
export default function Home(){
 const {store,state,connection}=useRescue();const [view,setView]=useState<'board'|'kitchens'|'history'>('board');
 const [modal,setModal]=useState<'help'|'import'|'settings'|'tools'|'reset'|null>(null);const [notice,setNotice]=useState('');const [error,setError]=useState('');const [input,setInput]=useState('');const [objective,setObjective]=useState<'rescue'|'distance'>('rescue');const [comparison,setComparison]=useState<{rescue:number;distance:number;scoreA:number;scoreB:number}|null>(null);
 const active=state.proposal?.assignments??state.approved;const total=state.donors.reduce((n,d)=>n+d.portions,0);const allocated=active.reduce((n,a)=>n+a.portions,0);const urgent=state.donors.filter(d=>d.deadline-state.now<=45&&d.deadline>=state.now).reduce((n,d)=>n+d.portions,0);const issues=validateAssignments(state,state.approved);const protectedCount=state.approved.filter(a=>a.locked).length;
 const act=(fn:()=>unknown,message?:string)=>{try{fn();setError('');setComparison(null);if(message)setNotice(message)}catch(e){setError(e instanceof Error?e.message:'Unable to complete action')}};
 const exportData=()=>{const {donors,kitchens,now,maxMinutes}=state;download('second-serve-dataset.json',JSON.stringify({donors,kitchens,now,maxMinutes},null,2))};
 const exportCSV=()=>act(()=>{if(!state.approved.length)throw new Error('Approve a plan first.');if(issues.length)throw new Error('Resolve the plan conflicts before exporting.');const m=manifest(state);download('second-serve-handoff.csv',[['Donor','Food','Kitchen','Portions','Estimated minutes','Protected'].map(csvCell).join(','),...m.rows.map(r=>Object.values(r).map(csvCell).join(','))].join('\r\n'),'text/csv;charset=utf-8')},'Handoff downloaded. No deliveries were dispatched.');
 return <main className="workspace"><header className="topbar"><a className="brand" href="/"><span className="brand-icon"><Leaf size={22}/></span>second serve<span className="brand-dot">.</span></a><span className="top-caption">GOOD FOOD. ANOTHER CHANCE.</span><button className={`connection ${connection==='connected'?'online':''}`} onClick={()=>setModal('tools')}><Radio size={12}/>{connection==='connected'?'6 WebMCP tools ready':connection==='checking'?'Connecting…':connection==='error'?'Agent connection failed':'Explore manually · connect an agent'}</button><span className="demo-badge"><span/>Demo workspace</span></header>
 <div className="shell"><aside className="sidebar"><div className="community"><span className="community-icon"><HandHeart size={21}/></span><div><strong>Community table</strong><small>Bengaluru · Evening rescue</small></div></div><div className="nav-label">WORKSPACE</div><button className={`nav-item ${view==='board'?'active':''}`} onClick={()=>setView('board')}><LayoutDashboard size={18}/>Rescue board<span>01</span></button><button className={`nav-item ${view==='kitchens'?'active':''}`} onClick={()=>setView('kitchens')}><HandHeart size={18}/>Community kitchens<span>{state.kitchens.length}</span></button><button className={`nav-item ${view==='history'?'active':''}`} onClick={()=>setView('history')}><History size={18}/>Activity trail<span>{state.audit.length}</span></button><div className="nav-divider"/><button className="nav-item" onClick={()=>setModal('import')}><Upload size={17}/>Bring your own data</button><button className="nav-item" onClick={()=>setModal('settings')}><Settings2 size={17}/>Scenario settings</button><div className="sidebar-note"><Leaf size={24}/><h3>More meals.<br/>Less waste.</h3><p>A shared workspace for people and their agents.</p><button className="text-button" onClick={()=>setModal('tools')}>Built with WebMCP <ArrowUpRight size={14}/></button></div><div className="sidebar-bottom"><Radio size={14}/>{store.isPersisted()?'Data stays in this browser':'Session only · storage unavailable'}</div></aside>
 <section className="main-area"><div className="heading-row"><div><div className="eyebrow">EVENING RESCUE · ILLUSTRATIVE SCENARIO · {time(state.now)}</div><h1>{view==='board'?'Every meal has a next stop.':view==='kitchens'?'Know who has room.':'A little clarity goes a long way.'}</h1><p>{view==='board'?'Match surplus food to the communities that need it.':view==='kitchens'?'Local knowledge makes the difference. Update capacity as conditions change.':'Every proposal, decision, and change — with its author.'}</p></div><Button variant="outline" className="soft-button" onClick={()=>setModal('help')}><CircleHelp/>How it works</Button></div>
 <nav className="mobile-nav" aria-label="Workspace"><Button variant={view==='board'?'secondary':'ghost'} onClick={()=>setView('board')}>Rescue board</Button><Button variant={view==='kitchens'?'secondary':'ghost'} onClick={()=>setView('kitchens')}>Kitchens</Button><Button variant={view==='history'?'secondary':'ghost'} onClick={()=>setView('history')}>Activity</Button><Button variant="ghost" size="icon" aria-label="Import data" onClick={()=>setModal('import')}><Upload/></Button><Button variant="ghost" size="icon" aria-label="Scenario settings" onClick={()=>setModal('settings')}><Settings2/></Button></nav>
 {error&&<div className="feedback error" role="alert"><TriangleAlert size={16}/><span>{error}</span><button aria-label="Dismiss error" onClick={()=>setError('')}><X size={15}/></button></div>}{notice&&<div className="feedback success" role="status"><Check size={16}/><span>{notice}</span><button aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={15}/></button></div>}
 <div className="metrics"><div><span>MEALS AVAILABLE</span><strong>{total}<small>portions</small></strong><p>Across {state.donors.length} food donors</p></div><div><span>{state.proposal?'PROPOSED FOR RESCUE':'IN YOUR APPROVED PLAN'}</span><strong>{allocated}<small>portions</small></strong><p>{state.proposal?'Awaiting your review':protectedCount?`${protectedCount} protected commitments`:'Ready for a second chance'}</p></div><div><span>COMMUNITY CAPACITY</span><strong>{state.kitchens.reduce((n,k)=>n+k.capacity,0)}<small>portions</small></strong><p>{state.kitchens.length} receiving kitchens</p></div><div className="urgent-metric"><span>TIME-SENSITIVE</span><strong>{urgent}<small>portions</small></strong><p><Clock3 size={13}/>Window ends within 45 minutes</p></div></div>
 {issues.length>0&&<div className="conflict-banner"><TriangleAlert size={18}/><div><strong>Conditions changed. This plan needs another look.</strong>{issues.map((i,n)=><p key={n}>{i}</p>)}</div><Button variant="outline" onClick={()=>act(()=>store.stage(objective))}>Replan</Button></div>}
 {view==='board'&&<><div className="board-grid"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">THE RESCUE NETWORK</span><h2>Good food, close to home</h2></div><span className="map-tag"><MapPin size={12}/>Bengaluru demo</span></div><Network state={state} assignments={active}/><div className="panel-footer"><span className="legend-dot"/>Donor <span className="legend-dot receiver-dot"/>Kitchen <span className="legend-dot locked-dot"/>Protected<span className="push-right">Connection diagram · estimated travel</span></div></section>
 <section className="panel copilot"><span className="agent-icon"><Sparkles size={22}/></span><div className="eyebrow">PEOPLE + AGENTS</div><h2>{state.proposal?'A second chance,\nready for review.':'Make room for\na better plan.'}</h2><p>{state.proposal?`${state.proposal.portions} portions matched. ${state.proposal.unassigned} still need a home. Review the proposal below before approving.`:'Your agent handles the matching. You bring the local knowledge and make the final call.'}</p><button className="prompt-card prompt-button" onClick={()=>act(()=>navigator.clipboard.writeText(agentPrompt).then(()=>setNotice('Prompt copied. Paste it into your browser agent.')).catch(()=>setError('Clipboard unavailable. Open How it works to select the prompt.')))}><span>“Find a home for these meals. Respect dietary needs and pickup windows.”</span><Copy size={13}/></button><label className="objective-label">PLANNING PRIORITY<select value={objective} onChange={e=>{setObjective(e.target.value as 'rescue'|'distance');setComparison(null)}}><option value="rescue">Rescue earliest-expiring first</option><option value="distance">Prefer shorter journeys</option></select></label><Button className="primary-button" onClick={()=>act(()=>store.stage(objective),'Proposal is ready for your review.')}><Sparkles/>{state.approved.length?'Rebuild rescue plan':'Build rescue plan'}<ArrowRight/></Button><div className="copilot-actions"><button onClick={()=>act(()=>{const a=plan(state,'rescue'),b=plan(state,'distance');setTimeout(()=>setComparison({rescue:a.portions,distance:b.portions,scoreA:a.score,scoreB:b.score}),0)})}><ArrowDownUp size={12}/>Compare priorities</button><button onClick={()=>setModal('tools')}><Braces size={12}/>Agent tools</button></div>{comparison&&<div className="comparison">Earliest first: <b>{comparison.rescue}</b> portions · {comparison.scoreA} portion-minutes.<br/>Shorter journeys: <b>{comparison.distance}</b> portions · {comparison.scoreB} portion-minutes.<small>Read-only comparison. Lower portion-minutes means less estimated travel per portion.</small></div>}<small>Built-in planner · or use your connected agent</small></section></div>
 {active.length>0&&<section className="plan-section"><div className="section-heading"><h2>{state.proposal?'Review your rescue plan':'Approved rescue plan'} <span>{active.length} assignments</span></h2><span className={state.proposal?'review-pill':'approved-pill'}>{state.proposal?'Proposal · not approved':'Approved · not dispatched'}</span></div>{state.proposal&&<div className="review-banner"><div><strong>{state.proposal.portions} portions have a place to go.</strong><p>{protectedCount} protected commitments kept. Travel and food suitability still require local verification.</p></div><Button variant="ghost" onClick={()=>act(()=>store.discard())}>Discard</Button><Button onClick={()=>act(()=>store.approve(),'Plan approved. Protect commitments or download the handoff.')}><Check/>Approve plan</Button></div>}
 <div className="assignment-list">{active.map(a=>{const d=state.donors.find(d=>d.id===a.donorId)!,k=state.kitchens.find(k=>k.id===a.kitchenId)!;const prev=state.approved.find(p=>p.id===a.id);return <article className={`assignment ${a.locked?'protected':''}`} key={a.id}><span className="assignment-count">{a.portions}<small>portions</small></span><div className="assignment-route"><strong>{d.name} <ArrowRight size={13}/> {k.name}</strong><p>{d.food} · {a.minutes} min estimated · arrive by {time(Math.max(state.now,d.ready)+a.minutes)}</p></div>{state.proposal&&!a.locked&&<span className="change-tag">{prev?(prev.portions===a.portions?'Kept':`${a.portions-prev.portions>0?'+':''}${a.portions-prev.portions} portions`):'New match'}</span>}<Button size="sm" variant={a.locked?'secondary':'ghost'} disabled={!!state.proposal} aria-label={`${a.locked?'Unlock':'Protect'} ${d.name} to ${k.name}`} onClick={()=>act(()=>store.lock(a.id))}>{a.locked?<LockKeyhole/>:<Unlock/>}<span>{a.locked?'Protected':'Protect'}</span></Button></article>})}</div>{state.proposal&&state.proposal.reasons.length>0&&<div className="unassigned"><TriangleAlert size={15}/><div><strong>{state.proposal.unassigned} portions still need a home</strong>{state.proposal.reasons.map(r=><p key={r.donorId}>{state.donors.find(d=>d.id===r.donorId)?.name}: {r.portions} portions. {r.reason}</p>)}</div></div>}
 {!state.proposal&&<div className="handoff-actions"><span><LockKeyhole size={13}/>Protect a commitment before asking your agent to replan.</span><Button variant="outline" onClick={exportCSV}><Download/>Download handoff</Button></div>}</section>}
 <div className="section-heading"><h2>Available to rescue <span>{state.donors.length} donors</span></h2><Button variant="ghost" size="sm" onClick={()=>setModal('import')}><Upload/>Import data</Button></div><div className="supply-list">{state.donors.map((d,i)=><div className="supply-row" key={d.id}><span className="donor-number">{String(i+1).padStart(2,'0')}</span><div><strong>{d.name}</strong><p>{d.food} · {d.allergens.length?d.allergens.join(', '):'No declared allergens'}</p></div><span className="diet-tag">{d.diet==='any'?'Non-vegetarian':d.diet}</span><span><strong>{d.portions}</strong> portions</span><span><Clock3 size={14}/>Until {time(d.deadline)}</span><span className="donor-progress" title="Assigned portions">{active.filter(a=>a.donorId===d.id).reduce((n,a)=>n+a.portions,0)}/{d.portions}</span></div>)}</div>
 <div className="disruption"><div><span className="eyebrow">TRY THE UNEXPECTED</span><h3>A kitchen calls. Their fridge is full.</h3><p>Set Open Table’s capacity to 30, then replan. Protected commitments stay yours.</p></div><Button variant="outline" disabled={!state.kitchens.some(k=>k.id==='k2')||state.kitchens.find(k=>k.id==='k2')?.capacity===30} onClick={()=>act(()=>store.update([{id:'k2',capacity:30}]),'Open Table can now take 30 portions. Rebuild the plan to adapt.')}><TriangleAlert/>Simulate capacity drop</Button></div></>}
 {view==='kitchens'&&<div className="kitchen-grid">{state.kitchens.map(k=>{const used=active.filter(a=>a.kitchenId===k.id).reduce((n,a)=>n+a.portions,0);return <article className="kitchen-card" key={`${k.id}-${k.capacity}`}><div className="kitchen-title"><HandHeart size={21}/><h2>{k.name}</h2><span>{k.id}</span></div><p>{k.diet==='any'?'Accepts all meal types':`${k.diet} only`} · Until {time(k.closes)}</p><div className="capacity-bar"><span style={{width:`${Math.min(100,k.capacity?used/k.capacity*100:100)}%`,background:used>k.capacity?'#b76a47':undefined}}/></div><div className="capacity-caption">{used} planned / {k.capacity} capacity</div><p>Excludes: {k.excludes.length?k.excludes.join(', '):'No declared exclusions'}</p><form onSubmit={e=>{e.preventDefault();const value=new FormData(e.currentTarget).get('capacity');act(()=>store.update([{id:k.id,capacity:Number(value)}]),`${k.name} capacity updated.`)}}><label htmlFor={`capacity-${k.id}`}>Available capacity</label><div><Input id={`capacity-${k.id}`} name="capacity" type="number" min="0" max="10000" required defaultValue={k.capacity}/><Button type="submit" variant="outline">Update</Button></div></form></article>})}</div>}
 {view==='history'&&<div className="history-panel"><div className="section-heading"><h2>Shared activity <span>Revision {state.revision}</span></h2><span>Last 50 events · current session</span></div>{state.audit.length===0?<div className="empty-state"><History size={28}/><h3>Your first decision starts the story.</h3><p>Build a plan, update a kitchen, or ask your agent to help.</p></div>:state.audit.slice().reverse().map((event,i)=><article className="audit-row" key={i}><span className={`actor-icon ${event.actor}`}>{event.actor==='agent'?<Sparkles size={16}/>:<HandHeart size={16}/>}</span><div><strong>{event.action}</strong><p>{event.actor==='agent'?'Browser agent via WebMCP':'You · workspace controls'} · revision {event.revision}</p></div><time>{new Date(event.at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time></article>)}</div>}
 <footer className="workspace-footer"><span>Illustrative data · planning aid · no deliveries dispatched</span><div><Button variant="ghost" size="sm" disabled={!store.canUndo()} onClick={()=>act(()=>store.undo(),'Previous change undone.')}><Undo2/>Undo</Button><Button variant="ghost" size="sm" onClick={()=>setModal('reset')}><RotateCcw/>Reset demo</Button></div></footer>
 </section></div>
 <Dialog open={modal!==null} onOpenChange={open=>{if(!open)setModal(null)}}><DialogContent className="app-dialog"><DialogTitle>{modal==='help'?'A shared table for you and your agent':modal==='import'?'Bring your own rescue data':modal==='settings'?'Scenario settings':modal==='reset'?'Start the demo again?':'Your app speaks agent'}</DialogTitle><DialogDescription>{modal==='tools'?'Real imperative WebMCP tools, connected to the same state you see on the board.':modal==='reset'?'This replaces the current workspace with the sample scenario. You can undo it.':'Second Serve · food-rescue planning workspace'}</DialogDescription>
 {error&&<p role="alert" className="dialog-error">{error}</p>}
 {modal==='help'&&<div className="help-content"><ol><li><strong>Read the room.</strong> Explore donor meals and kitchen constraints. All starting records are fictional.</li><li><strong>Build a proposal.</strong> Use the planner or paste the prompt below into a WebMCP-capable browser agent.</li><li><strong>Make it yours.</strong> Approve the plan, then protect assignments you have agreed locally.</li><li><strong>Adapt together.</strong> Change a kitchen’s capacity and ask the agent to replan. Review before exporting.</li></ol><Textarea readOnly value={agentPrompt} aria-label="Example agent prompt"/><p>The built-in button runs a deterministic optimizer. An external browser agent calls the registered tools; the app does not contain a pretend chat model or require an API key.</p><p>Travel times use illustrative coordinates, not roads or live traffic. Capacity, dietary labels and allergen exclusions are declared inputs, not food-safety verification. Data stays in this browser; reload restores inputs and clears plans for a fresh review.</p><Button onClick={()=>{setModal(null);act(()=>store.stage('rescue'))}}><Sparkles/>Try the planner</Button></div>}
 {modal==='tools'&&<div className="tool-content"><div className={`tool-status ${connection==='connected'?'online':''}`}><Radio size={16}/>{connection==='connected'?'Connected — all 6 tools registered':connection==='error'?'Registration failed — reload in a supported browser':'Open in ChatGPT’s in-app browser or a Chrome build with WebMCP enabled.'}</div>{toolDefinitions(store).map(t=><article key={t.name}><code>{t.name}</code><span>{t.annotations.readOnlyHint?'READ':'PROPOSE / UPDATE'}</span><p>{t.description}</p></article>)}<p className="tool-footnote">Mutations require the current revision. Human approval and unlocking are intentionally kept on the visible board. Registration supports document.modelContext with a navigator.modelContext compatibility fallback.</p></div>}
 {modal==='import'&&<div className="import-content"><p>Paste a JSON dataset with donors, kitchens, now (minutes after midnight), and maxMinutes. Up to 40 donors and 40 kitchens. Import replaces the current workspace; Undo restores it.</p><Button variant="outline" onClick={()=>{const {donors,kitchens,now,maxMinutes}=seed();setInput(JSON.stringify({donors,kitchens,now,maxMinutes},null,2))}}>Load example JSON</Button><Textarea value={input} onChange={e=>setInput(e.target.value)} placeholder='{"donors": [...], "kitchens": [...], "now": 1020, "maxMinutes": 35}' aria-label="Rescue dataset JSON" className="json-input"/><div className="dialog-actions"><Button variant="outline" onClick={exportData}><Download/>Export current data</Button><Button disabled={!input.trim()} onClick={()=>act(()=>{store.import(JSON.parse(input));setModal(null);setView('board')},'Dataset imported into this browser.')}><Upload/>Import dataset</Button></div></div>}
 {modal==='settings'&&<form className="settings-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),t=String(f.get('time')).split(':').map(Number);act(()=>{store.constraints(t[0]*60+t[1],Number(f.get('max')));setModal(null)},'Scenario updated. Build a fresh plan.')}}><label htmlFor="scenario-time">Scenario clock (does not advance automatically)</label><Input id="scenario-time" name="time" type="time" defaultValue={time(state.now)} required/><label htmlFor="max-minutes">Maximum estimated journey, minutes</label><Input id="max-minutes" name="max" type="number" min="5" max="90" defaultValue={state.maxMinutes} required/><p>Changing constraints clears a proposal and flags any approved assignments that no longer fit.</p><Button type="submit">Save settings</Button></form>}
 {modal==='reset'&&<div className="dialog-actions"><Button variant="outline" onClick={()=>setModal(null)}>Keep working</Button><Button onClick={()=>act(()=>{store.reset();setModal(null);setView('board')},'Demo restored. Ready for a new plan.')}><RotateCcw/>Reset demo</Button></div>}
 </DialogContent></Dialog>
 </main>;
}
