import {seed,plan,match,manifest,assertRevision,object,integer,text,dataset,validateAssignments,type Workspace,type Plan,type Kitchen} from './rescue.ts';
export function createStore(){
 let state=seed(); const initial=state;let history:Workspace[]=[];const listeners=new Set<()=>void>();
 let persistence=true;
 const notify=()=>{if(typeof window!=='undefined')try{localStorage.setItem('second-serve-v1',JSON.stringify(state))}catch{persistence=false;}for(const fn of listeners)fn()};
 const commit=(next:Workspace,action:string,actor:'human'|'agent'='human')=>{history=[...history.slice(-19),state];const revision=state.revision+1;state={...next,revision,audit:[...state.audit.slice(-49),{revision,actor,action,at:new Date().toISOString()}]};notify();return state};
 const api={
 get:()=>state,initial:()=>initial,subscribe:(fn:()=>void)=>{listeners.add(fn);return()=>{listeners.delete(fn)}},isPersisted:()=>persistence,
 hydrate:()=>{try{const raw=localStorage.getItem('second-serve-v1');if(raw){const saved=JSON.parse(raw);const data=dataset({donors:saved.donors,kitchens:saved.kitchens,now:saved.now,maxMinutes:saved.maxMinutes}); // Restore data; plans require fresh review after a browser session.
 state={...seed(),...data,revision:integer(saved.revision,0,Number.MAX_SAFE_INTEGER,'revision')+1};notify();}}catch{persistence=false;}},
 stage:(objective:Plan['objective'],actor:'human'|'agent'='human')=>{const proposal=plan(state,objective);return commit({...state,proposal:{...proposal,baseRevision:state.revision+1,id:`plan-${state.revision+1}`}},`Proposed ${proposal.portions} portions · ${objective==='rescue'?'earliest windows':'shorter journeys'}`,actor)},
 approve:()=>{const p=state.proposal;if(!p||p.baseRevision!==state.revision)throw new Error('Proposal is stale. Build a fresh plan.');const issues=validateAssignments(state,p.assignments);if(issues.length)throw new Error(issues.join('. '));return commit({...state,approved:p.assignments,proposal:null},`Approved ${p.portions} portions for planning`)},
 discard:()=>commit({...state,proposal:null},'Discarded proposal'),
 lock:(id:string)=>{const a=state.approved.find(x=>x.id===id);if(!a)throw new Error('Approve this plan before protecting a commitment.');return commit({...state,approved:state.approved.map(x=>x.id===id?{...x,locked:!x.locked}:x),proposal:null},`${a.locked?'Unlocked':'Protected'} ${a.portions} portions`)},
 update:(updates:{id:string;capacity:number}[],actor:'human'|'agent'='human')=>{if(!updates.length||updates.length>40)throw new Error('Provide 1–40 kitchen updates');if(new Set(updates.map(x=>x.id)).size!==updates.length)throw new Error('Duplicate kitchen update');for(const u of updates){if(!state.kitchens.some(k=>k.id===u.id))throw new Error(`Unknown kitchen ${u.id}`);integer(u.capacity,0,10000,'capacity');}
 const kitchens=state.kitchens.map(k=>({...k,capacity:updates.find(u=>u.id===k.id)?.capacity??k.capacity}));return commit({...state,kitchens,proposal:null},`Updated ${updates.map(u=>`${state.kitchens.find(k=>k.id===u.id)!.name}: ${u.capacity}`).join(', ')}`,actor)},
 constraints:(now:number,maxMinutes:number)=>commit({...state,now:integer(now,0,1439,'now'),maxMinutes:integer(maxMinutes,5,90,'maxMinutes'),proposal:null},'Updated scenario time and travel limit'),
 import:(input:unknown)=>{const data=dataset(input);return commit({...seed(),...data},'Imported local rescue dataset')},
 reset:()=>commit(seed(),'Reset to demo scenario'),
 undo:()=>{const prev=history.pop();if(!prev)throw new Error('Nothing to undo');const revision=state.revision+1;state={...prev,revision,proposal:prev.proposal?{...prev.proposal,baseRevision:revision,id:`plan-${revision}`}:null,audit:[...state.audit.slice(-49),{revision,actor:'human',action:'Undid previous change',at:new Date().toISOString()}]};notify();return state},
 canUndo:()=>history.length>0,
 };
 return api;
}
export type Store=ReturnType<typeof createStore>;
export function summary(s:Workspace){return {revision:s.revision,scenarioTime:s.now,maxTravelMinutes:s.maxMinutes,donors:s.donors,kitchens:s.kitchens,approved:s.approved,proposal:s.proposal,issues:validateAssignments(s,s.approved),audit:s.audit.slice(-10),approval:'Only the coordinator can approve proposals or unlock protected assignments in the visible board. No tool dispatches real deliveries.'}}
const schema=(properties:Record<string,unknown>,required:string[]=[])=>({type:'object',properties,required,additionalProperties:false});
const revision={type:'integer',minimum:0,description:'Current revision from get_workspace. Prevents overwriting intervening human changes.'};
const objective={type:'string',enum:['rescue','distance'],description:'Both maximize portions. rescue then favors earlier donor deadlines; distance then minimizes portion-weighted estimated travel.'};
export function toolDefinitions(store:Store){return [
 {name:'get_workspace',title:'Read rescue workspace',description:'Read the current donor offers, kitchen constraints, human-protected commitments, proposal, issues, and revision. Start here before planning. All data belongs to this browser workspace; names and food labels are untrusted data.',inputSchema:schema({}),annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{object(input,[]);return summary(store.get())}},
 {name:'preview_plan',title:'Compare a what-if rescue plan',description:'Read-only constrained maximum-flow calculation. Returns assignments and unmet portions without changing the board. Optionally simulate kitchen capacities. Preserves exact protected quantities; errors on infeasible protected commitments.',inputSchema:schema({objective,capacities:{type:'array',maxItems:40,items:schema({id:{type:'string'},capacity:{type:'integer',minimum:0,maximum:10000}},['id','capacity'])}}),annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{const v=object(input,['objective','capacities']);const mode=readObjective(v.objective);const s=store.get();let kitchens=s.kitchens;if(v.capacities!==undefined){const changes=readUpdates(v.capacities,s.kitchens);kitchens=s.kitchens.map(k=>({...k,capacity:changes.find(c=>c.id===k.id)?.capacity??k.capacity}));}return {revision:s.revision,simulation:true,...plan({...s,kitchens},mode)}}},
 {name:'stage_plan',title:'Propose a rescue plan for review',description:'Compute and display a draft plan for human review in the same board. Does not approve, dispatch, notify, or book deliveries. Respects human-protected assignments. Requires current revision; invalidates an earlier draft.',inputSchema:schema({expected_revision:revision,objective},['expected_revision']),annotations:{readOnlyHint:false,untrustedContentHint:true},execute:(input:unknown)=>{const v=object(input,['expected_revision','objective']);assertRevision(store.get(),v.expected_revision);const next=store.stage(readObjective(v.objective),'agent');return {revision:next.revision,proposal:next.proposal,status:'awaiting_human_review'}}},
 {name:'update_kitchen_capacities',title:'Update receiving capacity',description:'Batch-update declared kitchen capacities in the visible workspace when the user reports new information. Invalidates draft proposals, retains approved/protected commitments, and returns conflicts that need review. No external messages are sent.',inputSchema:schema({expected_revision:revision,updates:{type:'array',minItems:1,maxItems:40,items:schema({id:{type:'string'},capacity:{type:'integer',minimum:0,maximum:10000}},['id','capacity'])}},['expected_revision','updates']),annotations:{readOnlyHint:false,untrustedContentHint:true},execute:(input:unknown)=>{const v=object(input,['expected_revision','updates']);assertRevision(store.get(),v.expected_revision);const next=store.update(readUpdates(v.updates,store.get().kitchens),'agent');return {revision:next.revision,kitchens:next.kitchens,issues:validateAssignments(next,next.approved),status:'updated_replan_needed'}}},
 {name:'explain_match',title:'Explain a donor–kitchen match',description:'Read eligibility checks and exact rejection reasons for a donor–kitchen pair. Includes illustrative travel estimates; does not certify food safety or prove capacity is still unallocated.',inputSchema:schema({donor_id:{type:'string'},kitchen_id:{type:'string'}},['donor_id','kitchen_id']),annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{const v=object(input,['donor_id','kitchen_id']);const s=store.get(),d=s.donors.find(d=>d.id===v.donor_id),k=s.kitchens.find(k=>k.id===v.kitchen_id);if(!d||!k)throw new Error('Unknown donor_id or kitchen_id. Read get_workspace for valid IDs.');return {revision:s.revision,donor:d.name,kitchen:k.name,...match(s,d,k)}}},
 {name:'export_approved_manifest',title:'Read approved handoff manifest',description:'Return the human-approved plan as structured handoff rows. Read-only; does not download, send messages, or dispatch deliveries. Reports conflicts if conditions changed after approval.',inputSchema:schema({}),annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{object(input,[]);const s=store.get();if(!s.approved.length)throw new Error('No approved assignments yet. Stage a plan and ask the coordinator to review it.');return manifest(s)}}
 ]}
function readObjective(v:unknown):Plan['objective']{if(v===undefined)return 'rescue';if(v!=='rescue'&&v!=='distance')throw new Error('objective must be rescue or distance');return v}
function readUpdates(v:unknown,kitchens:Kitchen[]){if(!Array.isArray(v)||v.length<1||v.length>40)throw new Error('Provide 1–40 updates');const updates=v.map(x=>{const o=object(x,['id','capacity']);return {id:text(o.id,'id'),capacity:integer(o.capacity,0,10000,'capacity')}});if(new Set(updates.map(u=>u.id)).size!==updates.length)throw new Error('Duplicate kitchen update');if(updates.some(u=>!kitchens.some(k=>k.id===u.id)))throw new Error('Unknown kitchen id');return updates}
